apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-svc
  namespace: project
spec:
  clusterIP: None
  selector:
    app: todo-postgres
  ports:
    - port: 5432
      name: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-postgres
  serviceName: todo-postgres-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: todo-postgres
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todoapp-secret
                  key: DB_SUPER_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: 'local-path'
        resources:
          requests:
            storage: 1Gi
