apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - port: 1234
      targetPort: 4000
      protocol: TCP
      nodePort: 30080
