apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - port: 1234
      targetPort: 4000
      protocol: TCP
