apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: info
        configMap:
          name: log-output-cm
      - name: logs
        persistentVolumeClaim:
          claimName: pingpong-log-output-claim
      containers:
        - name: log-output-logger
          image: hiatusdev/log_output_logger
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
          volumeMounts:
          - name: logs
            mountPath: /app/logs
        - name: log-output-server
          image: hiatusdev/log_output_server
          env:
          - name: PINGPONG_SVC
            value: "http://pingpong-svc:2345"
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                key: MESSAGE
                name: log-output-cm
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
          volumeMounts:
          - name: logs
            mountPath: /app/logs
          - name: info
            mountPath: /app/info
          ports:
          - containerPort: 3001


