apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
  namespace: exercises
  labels:
    app.kubernetes.io/name: log-output-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: log-output-svc
                port:
                  number: 4444
          - pathType: Prefix
            path: '/pingpong'
            backend:
              service:
                name: pingpong-svc
                port:
                  number: 2345
          - pathType: Prefix
            path: '/get-pingpong'
            backend:
              service:
                name: pingpong-svc
                port:
                  number: 2345
